export enum UserRole {
  COLLABORATOR = 'COLLABORATOR',
  SETTLEMENT_COLLABORATOR = 'SETTLEMENT_COLLABORATOR',
  SETTLEMENT_AGENT = 'SETTLEMENT_AGENT',
  POINT_AGENT = 'POINT_AGENT',
  ADMIN = 'ADMIN',
}
